"""inital schema

Revision ID: 182a0d118ce6
Revises:
Create Date: 2026-05-18 01:28:01.158045

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "182a0d118ce6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
