"""expand schema to 8 tables

Revision ID: b1df1f5467d7
Revises: 182a0d118ce6
Create Date: 2026-06-02 22:39:20.606678

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "b1df1f5467d7"
down_revision: Union[str, Sequence[str], None] = "182a0d118ce6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archetype_analytics",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("archetype_name", sa.String(), nullable=False),
        sa.Column("total_sessions", sa.Integer(), nullable=False),
        sa.Column("total_flagged", sa.Integer(), nullable=False),
        sa.Column("average_score", sa.Float(), nullable=False),
        sa.Column("flag_rate", sa.Float(), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "daily_metrics",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("total_evaluations", sa.Integer(), nullable=False),
        sa.Column("total_fios_queries", sa.Integer(), nullable=False),
        sa.Column("total_yes_responses", sa.Integer(), nullable=False),
        sa.Column("total_no_responses", sa.Integer(), nullable=False),
        sa.Column("total_po_responses", sa.Integer(), nullable=False),
        sa.Column("total_cost_usd", sa.Float(), nullable=False),
        sa.Column("average_coherence_score", sa.Float(), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fios_queries",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("response", sa.Text(), nullable=False),
        sa.Column("coherence_score", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "archetype_scores",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("archetype_name", sa.String(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["evaluation_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fios_query_costs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("query_id", sa.String(), nullable=False),
        sa.Column("input_cost_usd", sa.Float(), nullable=False),
        sa.Column("output_cost_usd", sa.Float(), nullable=False),
        sa.Column("total_cost_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["fios_queries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transformer_results",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("question_id", sa.String(), nullable=False),
        sa.Column("response", sa.String(), nullable=False),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["evaluation_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "evaluation_sessions", sa.Column("user_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evaluation_sessions", "user_id")
    op.drop_table("transformer_results")
    op.drop_table("fios_query_costs")
    op.drop_table("archetype_scores")
    op.drop_table("fios_queries")
    op.drop_table("daily_metrics")
    op.drop_table("archetype_analytics")
    # ### end Alembic commands ###
